# Eksploracyjna Analiza Danych - Szkoły i Placówki Oświatowe w Polsce

## 1. Wstęp
Poniższy projekt ma na celu przeprowadzenie opisowej analizy wybranego zbioru danych z wykorzystaniem metod statystyki opisowej oraz odpowiednich narzędzi wizualizacyjnych. Analiza ta pozwoli na lepsze zrozumienie struktury danych, identyfikację zależności pomiędzy zmiennymi oraz wykrycie ewentualnych nieprawidłowości lub anomalii.

Jako temat analizy został wybrany **zbiór danych dotyczący szkół i placówek oświatowych w Polsce.** Dane te obejmują szeroki zakres informacji o jednostkach edukacyjnych. Wybór ten wynika z praktycznego znaczenia tych informacji. Dane o systemie oświaty są istotne zarówno z punktu widzenia administracji publicznej, jak i analiz społecznych. Dodatkowo duża liczba obserwacji oraz kolumn umożliwia zastosowanie różnych metod analizy oraz wizualizacji.

## 2. Opis zbioru danych
### Nazwa zbioru danych
Wykaz szkół i placówek oświatowych wg stanu bazy SIO na 30.09.2025

### Źródło danych
Analizowany zbiór danych pochodzi z portalu [dane.gov.pl](dane.gov.pl) i dotyczy wykazu szkół i placówek oświatowych w Polsce Dane pochodzą z Rejestru Szkół i Placówek Oświatowych (RSPO), który jest częścią Systemu Informacji Oświatowej (SIO). Rejestr zawiera informacje o wszystkich działających oraz zlikwidowanych szkołach i placówkach oświatowych w Polsce.

Poziom otwartości danych oceniono na ★★★★☆ (4/5), co oznacza wysoki stopień dostępności i przejrzystości danych publicznych. Dane zostały udostępnione 16 lutego 2026 r., a stan zbioru odpowiada danym dla 25 listopada 2025 r., co potwierdza jednolitość roku szkolnego (2025/2026) w analizowanym zbiorze, aczkolweik jest niespójne z wspomnianym w tytule terminem 30 września 2025 r.

**LINK:** [Wykaz szkół i placówek oświatowych](https://dane.gov.pl/pl/dataset/839,wykaz-szko-i-placowek-oswiatowych)



### Charakterystyka danych
Zbiór składa się z **ponad 50 tysięcy rekordów i 58 cech** - zawiera szczegółowe informacje o szkołach i placówkach edukacyjnych w Polsce, zarówno publicznych, jak i niepublicznych. Dane mają charakter tabularyczny i obejmują m.in.:

- **Zmienne jakościowe:**
    - nazwę placówki,
    - typ szkoły lub placówki (np. szkoła podstawowa, liceum, technikum),
    - dane adresowe i lokalizacyjne (województwo, powiat, gmina),
    - informacje o organie prowadzącym (np. gmina, fundacja),
    - status publiczno-prawny,
    - etap edukacji oraz specyfikę placówki
 

- **Zmienne numeryczne:**
    - liczba uczniów w placówce,
    - liczba dziewcząt w placówce,
    - liczba oddziałów w placówce.

Zbiór umożliwia analizę struktury systemu edukacji w Polsce, rozmieszczenia placówek, a także porównywanie szkół według różnych kryteriów (np. lokalizacji, typu czy organu prowadzącego). Dane mogą być wykorzystywane do analiz statystycznych, wizualizacji oraz badań nad systemem oświaty.

## Załadowanie bibliotek

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

## 3. Przygotowanie danych (Preprocessing)

In [2]:
df = pd.read_excel('wykaz_szkol.xlsx')

In [3]:
df.head()

,Rok szkolny,idTerytWojewodztwo,Wojewodztwo,idTerytPowiat,Powiat,idTerytGmina,Gmina,Typ gminy,Miejscowość,Czy szkoła,...,Organ rejestrujący,ucz_ogolem,w tym_ucz_dziewczeta,w tym_w oddz_przedszk,lb_oddz,etatUmowa,w tym_etat_niepełnozatr,lb_naucz_osoby,w tym_lb_naucz_pelnozatr,w tym_lb_naucz_niepelnozatr
0,2025/2026,2,DOLNOŚLĄSKIE,201,bolesławiecki,201011,Bolesławiec,M,Bolesławiec,0,...,POWIAT BOLESŁAWIECKI,NaN,NaN,NaN,NaN,45.36,6.36,52.0,39.0,13.0
1,2025/2026,2,DOLNOŚLĄSKIE,201,bolesławiecki,201011,Bolesławiec,M,Bolesławiec,1,...,POWIAT BOLESŁAWIECKI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025/2026,2,DOLNOŚLĄSKIE,201,bolesławiecki,201011,Bolesławiec,M,Bolesławiec,1,...,POWIAT BOLESŁAWIECKI,458.0,351.0,NaN,17.0,NaN,NaN,NaN,NaN,NaN
3,2025/2026,2,DOLNOŚLĄSKIE,201,bolesławiecki,201011,Bolesławiec,M,Bolesławiec,0,...,POWIAT BOLESŁAWIECKI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025/2026,2,DOLNOŚLĄSKIE,201,bolesławiecki,201011,Bolesławiec,M,Bolesławiec,1,...,POWIAT BOLESŁAWIECKI,59.0,43.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN

In [4]:
df.columns

Index(['Rok szkolny', 'idTerytWojewodztwo', 'Wojewodztwo', 'idTerytPowiat',
       'Powiat', 'idTerytGmina', 'Gmina', 'Typ gminy', 'Miejscowość',
       'Czy szkoła', 'idPodmiotGlowny', 'idPodmiotNadrzedny',
       'idTypPodmiotuNadrzednego', 'Typ podmiotu nadrzędnego', 'RSPO',
       'idTypPodmiotu', 'Typ podmiotu', 'idRodzajPlacowki',
       'Rodzaj szkoły/placówki', 'Nazwa placówki', 'Ulica', 'Numer domu',
       'Numer lokalu', 'Kod pocztowy', 'Poczta', 'Adres www', 'regon',
       'idPublicznosc', 'Publiczność', 'idKategoriaUczniow',
       'Kategoria uczniów', 'idSpecyfikaSzkoly', 'Specyfika szkoły',
       'idZwiazanieOrganizacyjneSzkoly', 'Związanie organizacyjne',
       'idTypOrgProw', 'Typ organu prowadzącego', 'typ_org_prow',
       'idOrganProwadzacy', 'Organ prowadzący', 'idTerytWojewOrgRej',
       'Organ rejestrującey - województwo', 'idTerytPowiatOrgRej',
       'Organ rejestrujący - powiat', 'idTerytGminaOrgRej',
       'Organ rejestrujący - gmina', 'idTypOrgRej',
       'Typ organu rejestrującego', 'Organ rejestrujący', 'ucz_ogolem',
       'w tym_ucz_dziewczeta', 'w tym_w oddz_przedszk', 'lb_oddz', 'etatUmowa',
       'w tym_etat_niepełnozatr', 'lb_naucz_osoby', 'w tym_lb_naucz_pelnozatr',
       'w tym_lb_naucz_niepelnozatr'],
      dtype='object')

In [5]:
df.shape

(55741, 58)

Zbiór danych składa się z 55 741 obserwacji oraz 58 zmiennych, co wskazuje na jego dużą szczegółowość i rozbudowaną strukturę. Każdy rekord odpowiada pojedynczej jednostce (szkole lub placówce oświatowej), jednak ze względu na sposób organizacji danych część informacji jest powielona - zmienne kategoryczne mają swój odpowiednik w postaci kolumn id.

In [6]:
df['Rok szkolny'].unique()

array(['2025/2026'], dtype=object)

In [7]:
df.drop('Rok szkolny', axis=1, inplace=True)

Analizowany zbiór obejmuje dane dla jednego roku szkolnego. Zarówno metadane, jak i analiza zawartości kolumny „Rok szkolny” wskazują, że wszystkie rekordy dotyczą roku szkolnego 2025/2026. Potwierdza to fakt, że kolumna ta przyjmuje wyłącznie jedną unikalną wartość, co oznacza brak zróżnicowania czasowego w analizowanym zbiorze. Kolumna ta zostałą usunięta.

In [8]:
df.describe()

,idTerytWojewodztwo,idTerytPowiat,idTerytGmina,Czy szkoła,idPodmiotGlowny,idPodmiotNadrzedny,idTypPodmiotuNadrzednego,RSPO,idTypPodmiotu,idRodzajPlacowki,...,idTypOrgRej,ucz_ogolem,w tym_ucz_dziewczeta,w tym_w oddz_przedszk,lb_oddz,etatUmowa,w tym_etat_niepełnozatr,lb_naucz_osoby,w tym_lb_naucz_pelnozatr,w tym_lb_naucz_niepelnozatr
count,55741.000000,55741.000000,5.574100e+04,55741.000000,55741.000000,16458.000000,16458.000000,55741.000000,55741.000000,55741.000000,...,55741.000000,38968.000000,38390.000000,21804.000000,38968.000000,29777.000000,29777.000000,29777.000000,29777.000000,29777.000000
mean,16.866795,1716.428876,1.716462e+06,0.758562,110098.163757,86068.484749,93.162656,113063.700777,30.286127,3.269622,...,130.642453,173.268400,86.878145,62.388736,9.120227,24.386710,3.497735,28.420358,20.863284,7.557074
std,8.893461,889.647894,8.896470e+05,0.427959,126054.225040,113901.593736,18.716297,121018.691965,37.533365,2.802054,...,1.480201,206.750761,112.820739,54.112399,8.317477,23.643584,4.216954,25.275281,21.801177,8.347337
min,2.000000,201.000000,2.010110e+05,0.000000,2874.000000,3021.000000,3.000000,2874.000000,1.000000,1.000000,...,120.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,10.000000,1061.000000,1.061011e+06,1.000000,22497.000000,15513.000000,100.000000,28146.000000,1.000000,1.000000,...,130.000000,47.000000,22.000000,22.000000,3.000000,8.320000,0.940000,11.000000,6.000000,3.000000
50%,14.000000,1465.000000,1.465011e+06,1.000000,64778.000000,39770.000000,100.000000,75044.000000,3.000000,1.000000,...,131.000000,103.000000,50.000000,45.000000,7.000000,16.810000,2.370000,21.000000,14.000000,6.000000
75%,24.000000,2465.000000,2.465011e+06,1.000000,127982.000000,109009.000000,100.000000,126917.000000,74.000000,7.000000,...,131.000000,212.000000,104.000000,91.000000,11.000000,33.990000,4.660000,39.000000,29.000000,10.000000
max,32.000000,3263.000000,3.263011e+06,1.000000,484847.000000,484653.000000,100.000000,484847.000000,100.000000,7.000000,...,133.000000,8978.000000,5506.000000,632.000000,127.000000,316.450000,101.710000,442.000000,309.000000,287.000000

In [9]:
counts = df.value_counts(['idTerytWojewodztwo', 'Wojewodztwo']).sort_index()
print(counts)

idTerytWojewodztwo  Wojewodztwo
2                   DOLNOŚLĄSKIE           3816
4                   KUJAWSKO-POMORSKIE     2796
6                   LUBELSKIE              3138
8                   LUBUSKIE               1370
10                  ŁÓDZKIE                3369
12                  MAŁOPOLSKIE            5589
14                  MAZOWIECKIE            8115
16                  OPOLSKIE               1523
18                  PODKARPACKIE           3415
20                  PODLASKIE              1624
22                  POMORSKIE              3387
24                  ŚLĄSKIE                6042
26                  ŚWIĘTOKRZYSKIE         1905
28                  WARMIŃSKO-MAZURSKIE    2087
30                  WIELKOPOLSKIE          5343
32                  ZACHODNIOPOMORSKIE     2222
Name: count, dtype: int64

In [10]:
df[df['Organ rejestrujący'] == 'GMINA CZYŻE']

,idTerytWojewodztwo,Wojewodztwo,idTerytPowiat,Powiat,idTerytGmina,Gmina,Typ gminy,Miejscowość,Czy szkoła,idPodmiotGlowny,...,Organ rejestrujący,ucz_ogolem,w tym_ucz_dziewczeta,w tym_w oddz_przedszk,lb_oddz,etatUmowa,w tym_etat_niepełnozatr,lb_naucz_osoby,w tym_lb_naucz_pelnozatr,w tym_lb_naucz_niepelnozatr
33515,20,PODLASKIE,2005,hajnowski,2005042,Czyże,Gm,Czyże,1,57599,...,GMINA CZYŻE,108.0,63.0,36.0,10.0,21.51,1.51,23.0,20.0,3.0

## 4. Statystyki opisowe

## 5. Wizualizacje

## 6. Porównanie względem cechy jakościowej

## 7. Analiza zależności między zmiennymi

## 8. Wnioski końcowe